# Generated by Django 3.0.5 on 2020-04-30 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kategoriProduk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('deskripsi', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='produk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(max_length=300)),
                ('status', models.BooleanField(default=True)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stok', models.IntegerField()),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.kategoriProduk')),
            ],
        ),
    ]
